### ISSUE TITLE
/usr/bin/python3 in IUS python3 packages

### ISSUE THREAD

**Issue by carlwgeorge** [iusrepo/packaging#1]
IUS maintains several python3 packages.  Currently that includes python34u, python35u, and python36u.  Since [replacing][replacement] stock python would break yum, these packages have to be [parallel installable][parallel] with stock python.  In 2014 we [received a request][hurie] to not only be be parallel installable with stock python, but also with other IUS python packages.  To do that to the existing packages at the time would have been too disruptive because it would involve removing the `/usr/bin/python3` symlink, among others.  In 2015 while [packaging python35u][gtmanfred], we decided to implement the change from the start of that package going forward.

A [differing opionion][madhavajay] was brought up in 2017, and [again][rahvee] a few days ago.  @rahvee has suggested a new hybrid approach that wasn't considered previously.  We could introduce a new optional subpackage to our spec files that contains the `/usr/bin/python3` symlink, as well other related symlinks such as `/usr/bin/pydoc3` and `/usr/share/man/man1/python3.1.gz`.  This subpackage would conflict with the corresponding subpackage from other python3 spec files, but the main package and other subpackages would continue to be fully parallel installable.  This would have no effect on existing users, and users who desire wish to opt-in to this new subpackage would get a `/usr/bin/python3` symlink.  Switching between IUS python3 stacks would be more complicated for those users, but would be similar to IUS replacement packages.

```
# yum shell
> erase python36u-main
> install python37u-main
> run
```

We would like to gather more feedback from the community before making a decision on this change.

[replacement]: https://ius.io/SafeRepo/#safe-replacement-package
[parallel]: https://ius.io/SafeRepo/#parallel-installable-package
[hurie]: https://bugs.launchpad.net/ius/+bug/1358202
[gtmanfred]: https://github.com/iuscommunity/wishlist/issues/17
[madhavajay]: https://github.com/iuscommunity-pkg/python36u/issues/2
[rahvee]: https://github.com/iuscommunity-pkg/python36u/issues/4

**Comment by rahvee** [comment]
Thank you for considering this possibility and remaining open to revisit decisions that were made in the past. Not all communities remain open minded after decisions were made before, and this is refreshing.

To make this proposal explicitly clear, the problem is the absence of the `/usr/bin/{python3,pydoc3,pyvenv,pip3}` binaries. It is a widely adopted pattern to use `#!/usr/bin/env python3` as the shebang for scripts, and to use `pip3 -r requirements.txt` and/or `pyvenv` to install dependencies and create virtual environments. The changes that were introduced in IUS python3.5 and above explicitly do not provide these executables, which requires script maintainers to update their scripts to use explicit python versions like `#!/usr/bin/env python3.6`. This might be a reasonable expectation for developers developing their own code, but many python scripts are community provided, installed from various yum repos and git projects.

The proposal is to provide an additional package, for example named `python36u-symlinks` or some similar name, which only contains the symlinks that would have otherwise caused a conflict between different versions of `python35u` vs `python36u` vs `python37u` and so on. This includes the aforementioned `/usr/bin/{python3,pydoc3,pyvenv,pip3}` symlinks, and `/usr/share/man/man1/python3.1.gz`. (Are there any other conflicting files, or is that all?) Sysadmins would be able to search `yum provides /usr/bin/python3` and would discover `python34u`, `python35u-symlinks`, `python36u-symlinks` and so on. In the present day, sysadmins searching for `/usr/bin/python3` are easily misled to think `python34u` is the latest available. 

The various `python3xu-symlinks` packages must conflict with each other, and with `python34u` unless `python34u` can also have the conflicting parts broken out into a subpackage. The various `python3xu-symlinks` packages must depend on the corresponding binary packages. For example, `python36u-symlinks` must depend on `python36u` which provides the target of the symlink, `/usr/bin/python3.6`.

Any users who are already accustomed to manually creating the symlinks for `python35u` etc, do not need to take the `-symlinks` subpackages. They may continue as they are. But any users who do not expect the manual symlink process, will find the optional use of the `-symlinks` subpackage to be more desirable. For example, I am a typical devops engineer, using puppet, chef, salt, ansible, etc to manage 1,400 systems, and the normal expected technique to update/upgrade tools such as python is to simply search for which package provides the tool, and then add that package to puppet, etc. Yes it's possible for config management tools to maintain the symlink, but there is no easy or customary way for sysadmins or devops engineers to know that such a step is necessary. It's highly unusual and unexpected. When I searched for `yum provides /usr/bin/python3` I found only `python34u`, but if I had found `python34u` and `python35u-symlinks` and `python36u-symlinks` etc, it would have been instantly obvious what happened, and what I need to do in order to get the desired python 3.6.

**Comment by carlwgeorge** [comment]
> pip3

We can discuss a similar approach for a `/usr/bin/pip3` symlink, but to be clear that is not part of the main python package.  [python35u-pip][python35u-pip] and [python36u-pip][python36u-pip] have their own spec files.

> which requires script maintainers to update their scripts

It actually doesn't.  Python scripts can be run with `python3.6 script.py` and the shebang line is ignored.  For python modules with commands, running `python3.6 setup.py install` will create entry point scripts with `#!/usr/bin/python3.6` shebangs lines corresponding to the version of python they were created with.  For virtual environments, running `python3.6 -m venv foo` creates all the symlinks you could hope for, including `foo/bin/python`, `foo/bin/python3`, `foo/bin/pip`, and `foo/bin/pip3`.  These simple workarounds are why I believe we have only had two issues reported about this in almost 2.5 years since we released python35u.

> Are there any other conflicting files, or is that all?

Spread across the main package and the -libs, -devel, -tools subpackages, we have:

```
/usr/bin/python3
/usr/bin/python3-config
/usr/bin/python3-debug
/usr/bin/pydoc3
/usr/bin/pyvenv
/usr/bin/idle3
/usr/bin/2to3-3
/usr/lib64/libpython3.so
/usr/lib64/pkgconfig/python3.pc
/usr/share/man/man1/python3.1.gz
```

We don't necessarily have to include all of these.  In fact I think only the commands and manpages are worth considering for this.

> sysadmins searching for /usr/bin/python3 are easily misled

Speculating on the majority experience based on your experience isn't a worthwhile endeavor.  I could argue that it's more common for sysadmins to run `yum search python3`, but we have no way to accurately determine which is more common.  Let's just focus on the desired outcome.

> unless python34u can also have the conflicting parts broken out into a subpackage

This isn't likely, as moving the symlinks to an optional subpackage would remove them from the main package and from existing installations.

> python36u-symlinks

This is a less important detail, but I'm not a fan of that naming.  It focuses on the implementation rather than the purpose.  python36u-main is more appropriate in my opinion.

[python35u-pip]: https://github.com/iuscommunity-pkg/python35u-pip
[python36u-pip]: https://github.com/iuscommunity-pkg/python36u-pip

**Comment by rahvee** [comment]
I agree, `python36u-main` is better.

**Comment by b-harper** [comment]
@rahvee,

Thanks for the detailed explanation of your proposal.  Historically, the Red Hat solution for this type of symlink management has been `alternatives`.  Java and mail servers are the examples that always come to my mind, like the following:

```
$ repoquery --whatprovides /usr/sbin/sendmail
sendmail-0:8.14.7-5.el7.x86_64
ssmtp-0:2.64-14.el7.x86_64
exim-0:4.90.1-2.el7.x86_64
opensmtpd-0:6.0.3p1-1.el7.x86_64
postfix-2:2.10.1-6.el7.x86_64
postfix32u-2:3.2.5-1.ius.centos7.x86_64
```

If only single one of these packages are installed, the symlink will be created for that application:

```
$ /usr/sbin/sendmail
Exim is a Mail Transfer Agent. It is normally called by Mail User Agents,
not directly from a shell command line. Options and/or arguments control
what it does when called. For a list of options, see the Exim documentation.
```

Like I  mentioned in iuscommunity-pkg/python36u#2, there is no clear cut best solution and I have mixed thoughts if `alternatives` is a good idea.  

I am curious if others have concerns with our current approach and if so, how should we proceed.

**Comment by yodermk** [comment]
I was also thinking of the alternatives system.  Seems that should be preferable unless there is a compelling reason to not use it.

**Comment by rahvee** [comment]
@b-harper @yodermk I don't see any past discussion about the alternatives system. Did that take place somewhere else? I can't see any compelling argument against it...

To @b-harper comment about "curious if others have concerns with the current approach," and to @carlwgeorge comments about speculating what other sysadmins do, and comments about having only a tiny number of users reporting issues over ~2.5 years: The university I work for has about 2 dozen linux sysadmins and 2,000 systems, so to the extent our group is typical of mid-to-large scale deployments, I'm not speculating what others do. They typically don't communicate feedback of this nature or participate in the community. In this regard, I am personally a slim minority. At first, we just used the base redhat python34 package, until we needed pip about 1.5 years ago, which prompted us to install the IUS packages. It was not clear how to make python35u or python36u operational, because if we ran the `python3.6 install` workaround mentioned, it would modify scripts that are under git control, and if we hard-coded python3.6 into python scripts, there are hundreds of scripts to edit and it seems like a bad idea, and if we launched the scripts using `python3.6 somescript.py` it would require modifying bash scripts that call python scripts so it's just moving the hard-coded value to a different location. None of these are workable solutions for us. I know we're not the only type of consumers - there are also users doing software development on their laptops and so on, whose environments are different from ours, and they might be able to use those workarounds. How representative our group is to other groups, I cannot say, but what our group did was: for ~1.5 years until now, we just used python34u, because python >= 35u didn't seem ready; if we deployed it, we would have to solve issues. Now we have users that require python >= 3.5, so I'm being forced to address the issue. The workaround I've settled on for now is to use puppet to create the symlinks, in all the manifests where puppet installs python35u or python36u, but until I came here and talked about it, it was very unclear that I was supposed to do that, and it was unclear if I was doing a nonstandard behavior that would cause some sort of unexpected problem, and it was unclear which links should exist. I had to figure that all out on my own. It's not as if there are instructions readily available, that say I need to do these steps. I think it's fair to say all the steps we've followed, and all the solutions we've followed, are very typical for mid-to-large infrastructures. They are typically just avoiding the >= 3.5 packages until they have to, and after some effort, they end up creating symlinks without reporting feedback to the community. I think either the proposed package that provides symlinks, or using the alternatives system, would be better than providing nothing. At least then consumers could follow a standard practice and know what to expect.

**Comment by b-harper** [comment]
> @b-harper @yodermk I don't see any past discussion about the alternatives system. Did that take place somewhere else?

It was mentioned in iuscommunity-pkg/python36u#2. Initially, we did not give it too much thought.  I wanted to bring it up here as another possible solution.

> The workaround I've settled on for now is to use puppet to create the symlinks, in all the manifests where puppet installs python35u or python36u, but until I came here and talked about it, it was very unclear that I was supposed to do that, and it was unclear if I was doing a nonstandard behavior that would cause some sort of unexpected problem, and it was unclear which links should exist.

If confusion is the root of the issue, maybe we should update documentation instead of making packaging changes.

**Comment by rahvee** [comment]
When somebody does `yum install python35u` or similar, there is no well-known documentation location for extra steps needed beyond the yum install. Nobody's going to know they need to look at documentation, and even if the thought crossed their minds, it wouldn't be clear where to look - man pages? python website? ius website? etc, at best, people might try google, and by that time, you've already lost them. Nobody expects they need to google "how to yum install ius python." Everybody would assume the answer is written in the question. It's not as if yum pops up an installation dialogue or anything of the nature. Unless there's a compelling reason not to use symlinks or the alternatives system, or at least make the option available... It would be better to do so.

**Comment by carlwgeorge** [comment]
The documentation is `rpm -ql python35u`.  In any package, if the command isn't named how you like, you can set up your own symlink or alias.

**Comment by rahvee** [comment]
Oh well, sorry to see it come to that. I thought I made some pretty reasonable points and a very simple reasonable request that would obviously be better for everyone (or at least break-even, since it's optional anyway). The one last point I guess I'll add is: browse github and search for python3. Literally everybody uses `#!/usr/bin/env python3` so it's a bummer the conclusion is "fix it yourself" and "there is no documentation" cleverly combined into a condescending statement, as if it's impossible or even difficult to do better, and annoying that someone from the community would have the audacity to ask. ¯\_(ツ)_/¯

**Comment by carlwgeorge** [comment]
@rahvee No conclusion has been made, I was simply responding to your critique about documentation.  I was not trying to be condescending.  If I was annoyed at your inquiry, I wouldn't have opened this issue to discuss it further.  You've made you're point multiple times that usage of `#!/usr/bin/env python3` is common; we understand.  We want to look forward at possible ways to improve the packages, not to keep rehashing the way things have been.

**Comment by rahvee** [comment]
I don't think I critiqued documentation. I pointed out that there's no reasonable way to communicate to users that any documentation needs to be followed - It's just a characteristic of yum, that there is basically no such thing as exposing documentation to users who install packages via yum. Sorry my comment felt like criticism, and sorry your response also felt unfriendly to me. I'm happy to move on... I haven't heard any reasons *opposed* to the proposals, or offering other proposals...

**Comment by rahvee** [comment]
There is one thing I think is clear from all the conversation above: There exist possible ways to solve the problem, including either an extra rpm to provide the symlinks or by using the alternatives system. There may be differing opinions about which of these is better than the other, but there's no ambiguity that both options are better than the status-quo of having nothing (the user must provide their own symlinks). One of our developers recently encountered this: [adobe user-sync](https://github.com/adobe-apiplatform/user-sync.py) where they instruct users to install IUS python 3.4+ and they've hard-coded their script to python3.6 and distribute a binary pex package with that built-in. We can criticize them for doing bad packaging, but they're a major vendor demonstrating that these decisions (or lack thereof) will trickle down to real users in the real world. Please find a way to pick a solution and go with it - doesn't matter which one - as long as there's a solution.

**Comment by carlwgeorge** [comment]
I'm working on an [upgrade path](https://github.com/iusrepo/packaging/issues/7) that will move users from python36u to the new python3 package that was added to RHEL 7.7.  That package includes `/usr/bin/python3`, which will take care of this issue.  Subscribe to https://github.com/iusrepo/packaging/issues/7 for future updates.
